package entity;
// Generated 19 mai 2023 23:10:05 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Medecin generated by hbm2java
 */
@Entity
@Table(name="medecin"
    ,schema="gestionmed"
)
public class Medecin  implements java.io.Serializable {

    public Medecin() {
    }

    public Medecin(String grade, String nom, String prenom) {
       
       this.grade = grade;
       this.nom = nom;
       this.prenom = prenom;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    //@OneToMany(mappedBy = "medecin", cascade = CascadeType.ALL)
    //private List<Visiter> visites;

    // Autres attributs et méthodes de l'entité Medecin

   //public List<Visiter> getVisites() {
       //return visites;
    //}

   /// public void setVisites(List<Visiter> visites) {
       // this.visites = visites;
    //}
     
    @Column(name="codemed", unique=true, nullable=false)
     private int codemed;
     
    public int getCodemed() {
        return this.codemed;
    }
    
    public void setCodemed(int codemed) {
        this.codemed = codemed;
    }

    
    @Column(name="grade")
    private String grade;
    
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }

    
    @Column(name="nom")
    private String nom;
    
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom")
     private String prenom;
    
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }




}


