package entity;
// Generated 19 mai 2023 23:10:05 by Hibernate Tools 4.3.1




import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name="patient"
    ,schema="gestionmed"
)
public class Patient  implements java.io.Serializable {


     private int codepat;
     private String adresse;
     private String nom;
     private String prenom;
     private String sexe;
    

    public Patient() {
    }

    public Patient(String adresse, String nom, String prenom, String sexe) {
       this.adresse = adresse;
       this.nom = nom;
       this.prenom = prenom;
       this.sexe = sexe;
    }
    
    
     @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="codepat", unique=true, nullable=false)
    public int getCodepat() {
        return this.codepat;
    }
    
    public void setCodepat(int codepat) {
        this.codepat = codepat;
    }

    public void incrementCodePat() {
        // Vous pouvez ajouter des logiques supplémentaires ici, comme la récupération du dernier codePat dans la base de données
        this.codepat++;
    }
    
    @Column(name="adresse", length=50)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="nom", length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", length=50)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="sexe", length=20)
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }




}


